### PR TITLE
Add WebSocket heartbeat

### LINKED ISSUE #99: Handle close broken connections
How are you guys handling broken connections? Something like [this](https://github.com/websockets/ws/blob/355d24a2db2c32a8ed7b2b820ddf60e511f26d7c/README.md#how-to-detect-and-close-broken-connections) should be integrated into the code right?

### PR DESCRIPTION
**Pull request by fixe**
Fixes #99.

### CODE REVIEW

**Comment by tjaartvdwalt** [comment]
Could we merge this patch? It would solve a problem for me.

**Comment by FlyveHest** [comment]
This would be very nice, i've been experiencing a lot of "silent disconnects" lately.

**Comment by FranciscoKnebel** [comment]
Good, it's not only me. I have two bits with silent disconnects. Process still running, no error messages, but disconnected to Slack. I suppose the connection should just be renewed (Aka restart), so detecting if connection is still up is needed.

**Comment by FranciscoKnebel** [comment]
While this PR isn't merged, I added the same logic to my bots by adding the heartbeat on handling the 'open' websocket event, which is emitted after ws is defined, so you can use it there.

**Comment by smartpierre** [comment]
Can you merge this ? Silent disconnect are a real problem.

**Comment by mishk0** [comment]
did it. Sorry for the delay %)

**Comment by Dam-Buty** [comment]
thx @mishk0 you rock 💪

**Pull request merged**
