### PR TITLE
Emit an error instead of throwing one when login fails

### PR DESCRIPTION
**Pull request by gpanders**
Issue #35

### CODE REVIEW

**Comment by bmul937** [comment]
what if listener of error event not registered before error event raised? will this still crashing the app?

**Comment by gpanders** [comment]
@bmul937 if you change the line to

    this.emit('error', data.error);

it will throw an error if there is no error event listener. This might actually be preferred behavior so that it doesn't fail silently if there is no error event listener.

**Comment by mishk0** [comment]
Could you add that event in readme.md?

**Comment by gpanders** [comment]
@mishk0 Done

**Pull request merged**
